# Site settings
title: Cooking Teach
description: All New Indian,South Indian and World wide HomeMade Recipes
baseurl: ""
url: "https://cookingteach.com"
logo: '/assets/logo.png'
# User settings
username: Cooking Teach
user_description: All New Indian,South Indian and World wide HomeMade Recipes
user_title: Cooking Teach
email: rupsaini93@gmail.com
twitter_username: cookingteach
github_username:  cookingteach
gplus_username:  cookingteach
disqus_username: cookingteach

paginate: 6
paginate_path: /page/:num/
infinite_scroll: false
#gems: ["jekyll-paginate","jekyll-redirect-from"]

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: /:title


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Categories
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
