---
title: Cooking Teach | Homemade Easy Recipes
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: All Indian,South Indian and World wide HomeMade Recipes. Learn how to
  make delicious recipes at home.
baseurl: ''
url: https://cookingteach.com
img_url: https://cookingteach.com/wp-content/uploads
logo: "/assets/logo.png"
username: Cooking Teach
user_description: All Indian,South Indian and World wide HomeMade Recipes.Learn how
  to make delicious recipes at home.
user_title: Cooking Teach
email: support@cookingteach.com
twitter_username: cookingteach
github_username: cookingteach
gplus_username: cookingteach
disqus_username: cookingteach
paginate: 6
paginate_path: "/page/:num/"
infinite_scroll: false
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: "/:title"
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false
links:
- title: Home
  url: "/"
- title: Series
  url: "/series"
- title: Tags
  url: "/tags"
- title: About Me
  url: "/about"
exclude:
- package.json
- src
- node_modules
